name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build
        run: mvn -ntp -B package --file pom.xml
      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_PROJECT: Ouest-France_${{ github.event.repository.name }}
        run: mvn -ntp -B sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} -Dsonar.projectKey=$SONAR_PROJECT -Dsonar.branch.name=${GITHUB_REF##*/}
      - name: Prepare Settings
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: '[{ "id": "central", "username": ${{ secrets.OSSRH_USERNAME }}, "password": ${{ secrets.OSSRH_TOKEN }} }]'
      - name: Deploy Snapshot
        run: mvn -ntp -B deploy -DskipTests=true
