name: Deploy Package

on:
  release:
    types: [edited]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Info
        run: |
          echo "Launch info $${{ github.event.inputs }}"
          echo "Release version: ${{ github.event.inputs.releaseVersion }}, Development version: ${{ github.event.inputs.developmentVersion }}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
