name: Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Display versions
        run: |
          echo "Release Target_Commitish ${{ github.event.release.target_commitish }}"
          echo "Release Tag_Name ${{ github.event.release.tag_name }}"
          echo "Release Name ${{ github.event.release.name }}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions[bot]@github.com'
          mvn -ntp -B release:prepare release:perform -DreleaseVersion=${{ github.event.release.tag_name }} -Dtag=tmp_${{ github.event.release.tag_name }}
      - name: Post-Release
        run: git push --delete origin tmp_${{ github.event.release.tag_name }}
