name: Renovate

on:
  schedule:
    - cron: '0 8 * * 1-5'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
